### ISSUE TITLE
NoClassDefFoundError of <TraceScript> in JBoss EAP7

### ISSUE THREAD

**Issue by daleqq** [btraceio/btrace#282]
I use the basic `btrace <pid> <TraceScript>.java` command to trace my program which is an ear deployed in JBoss EAP7. When I access the target function, the error below is prompted:
```
10:13:28,264 ERROR [stderr] (default task-50) java.lang.NoClassDefFoundError: <TraceScript>$1
10:13:28,265 ERROR [stderr] (default task-50) 	at <myApplication>.View.$btrace$<TraceScript>$1$onGetSQLReturn(Unknown Source)
10:13:28,265 ERROR [stderr] (default task-50) 	at <myapplication>.View.getSQL(View.java:519)
```
I think it is caused by JBoss Modules class loading, I add `-Djboss.modules.system.pkgs=com.sun.btrace` parameter but not solved the problem.

Is there any solution to this ? Or should I use some other ways to trace the program?

Thanks.

**Comment by jbachorik** [comment]
The problem is accessing the probe class, not the BTrace internal classes. Therefore `-Djboss.modules.system.pkgs=com.sun.btrace` can not help here.
The probe class is loaded by bootstrap class loader - but it seems like JBoss class loader will not delegate to that CL when search for classes. 

Can you do an experiment and declare a package in the probe script (standard `package my.package` statement in the source will do) and then run the app with -Djboss.modules.system.pkgs=com.sun.btrace,my.package` (or whatever delimiter is used in the list of packages).

**Comment by daleqq** [comment]
@jbachorik Thank you very much. I add the package of my probe class into `-Djboss.modules.system.pkgs` parameter, and the trace works.
