### ISSUE TITLE
Not able to monitor application deployed in weblogic using Btrace

### ISSUE THREAD

**Issue by Tapan2609** [btraceio/btrace#313]
Hi @jbachorik
How to instrument application classes when there are multiple deployments in weblogic. If we specify weblogic's PID, It will instrument only weblogic internal classes. Is it possible to attach btrace to a single deployment in a weblogic server?

I have attached Btrace script and debug logs.
[Tracing-script-logs.tar.gz](https://github.com/btraceio/btrace/files/1654887/Tracing-script-logs.tar.gz)

**Comment by jbachorik** [comment]
The script seems to be stuck at the beginning of instrumentation, according to the logs. Is there any more info in weblogic logs?
There should be no difference from tracing any other Java application - unless weblogic uses OSGI-like class isolation which would require a special config in order to make BTrace classes reachable as bootstrap classes.

**Comment by Tapan2609** [comment]
Hi Bachorik,

Thanks for update.

Fortunately we were able to monitor weblogic 12c server with btrace script.

Only challenge is we are not able to monitor weblogic 11g servers with
btrace script.

There might be issues with java versions like 12c is completely built on
java 8 and 11g is on java 6.

We shall update you if we get any solution for this.

Once again thanks for support.

Thanks,
Tapan Hegde

**Comment by jbachorik** [comment]
BTrace does not support JDK 6, sorry.
