### ISSUE TITLE
my java script is too Bigger,can't run

### ISSUE THREAD

**Issue by flameOnYou** [btraceio/btrace#325]
i use freemarker to product a java script ,when I run btrace PID xxx.java ，it Be like can't run. and i reduce the script num, btrace will be work. how can i use a long java script

**Comment by jbachorik** [comment]
The method size limit in bytecode is 65k. Since BTrace compiler wraps your code with some extra code it may happen that the size limit will be crossed.

If you need all that code you should consider extracting the shareable part as a BTrace extension ([a short writeup](http://btraceio.github.io/btrace/2014/09/extensible-services/)). Take a look at the [Printer service](https://github.com/btraceio/btrace/blob/master/src/share/classes/com/sun/btrace/services/impl/Printer.java) for inspiration how to write a new extension.

**Comment by jbachorik** [comment]
Closing.
