### ISSUE TITLE
Issue with using BTrace with kotlin coroutines

### ISSUE THREAD

**Issue by kushal-ti** [btraceio/btrace#557]
I'm trying to use BTrace on a kotlin webserver which uses coroutines and it leads to frequent NullPointerExceptions. On top of this, it seems BTrace onReturn method is also failing to accurately measure time of execution on coroutines
Is there any wayto get BTrace working normally with coroutines, or at the very least do you know what part of BTrace could be causing an issue with coroutines specifically

**Comment by jbachorik** [comment]
There might be several issues here.
- NPE - could you run BTrace in debug mode and attach the captured logs here?
- measuring coroutine duration - I think this might be a bit tricky because it is not a normal code but, well, coroutines. I don't know the full implementation details of Kotlin coroutines but it is very possible that the code might get split into multiple synthetic methods and you would need to track all of them (but this is mostly handwaving). The best would be if you could run BTrace with `-d <path to dumped classes>` option to store the instrumented classes in the given path and attach the class containing the coroutine to this issue as well.
